name: Flutter CI

on:
  pull_request:
    branches: ["develop"]

jobs:
  flutter_checking:
    name: Flutter Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.1"
          cache: true

      - name: Install dependencies
        run: |
          cd code
          flutter pub get

      - name: Check code formatting
        run: |
          cd code
          flutter format --set-exit-if-changed .

      - name: Run Flutter analyze (Linting)
        run: |
          cd code
          flutter analyze

      - name: Run Flutter tests
        run: |
          cd code
          flutter test
